### ISSUE TITLE
Editor raw on the fly markdown support

### ISSUE THREAD

**Issue by Ali-TM-original** [enassi/enassi#10]
Currently when you write any markdown in the editor it does not get formatted as seen in the below screenshot. It would be cool if the editor could convert markdown into it's proper visual representatino on the fly.

![image](https://github.com/enassi/enassi/assets/76595455/7af4ca35-0bf7-4ae5-9ee5-1b16792238db)

**Comment by newproplus** [comment]
Yes, because the editor is based on editorjs which is a block-style editor, so it cannot use as a standard markdown editor.
If you could get some basic usage of editorjs, you can visit https://editorjs.io/, in the home page, there are screenshots showing you a few buttons that you can add or edit the content.
In the future, we will add a standard markdown editor, then the type will be markdown, not note. We are thinking about which editor is more suitable，currently maybe milkdown (https://milkdown.dev/).

**Comment by Ali-TM-original** [comment]
Ahh, I see. well, editorjs is limiting. milkdown seems like a better alternative I would suggest you look at Simplemde (https://github.com/search?q=simpleMDE&type=repositories) but that is unmaintained and pretty old
